"""
Central configuration of the final experiment.

Every value below is the one used for the final result data. Literature
references for the design decisions are in docs/literaturliste.md.
"""

from pathlib import Path

from dotenv import load_dotenv

# Loads environment variables from a .env file in the project root (notably
# OPENAI_API_KEY). Must happen before any os.environ access — config.py is
# imported first by every other module, so this is the single central place.
load_dotenv()

# --- Project paths ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
INSTANCES_DIR = DATA_DIR / "instances"
RESULTS_DIR = DATA_DIR / "results"
LOGS_DIR = DATA_DIR / "logs"
DOCS_DIR = PROJECT_ROOT / "docs"

# --- Reproducibility ---
RANDOM_SEED = 42  # central seed for both instance generators
# Per-instance seed convention used by both generators:
#     seed = RANDOM_SEED + size * 1000 + instance_index

# --- Instance sizes ---
# Both problems use the SAME five nominal size levels. This gives a
# consistent experimental structure and presentation across problem classes;
# it does NOT imply equal computational complexity between SMTWTP n=25 and
# SICLSP T=25.
SMTWTP_SIZES = [5, 10, 15, 20, 25]   # number of jobs n
SICLSP_SIZES = [5, 10, 15, 20, 25]   # number of periods T
INSTANCES_PER_SIZE = 5

# Backwards-compatible aliases used by the two generators.
SMTWTP_INSTANCES_PER_SIZE = INSTANCES_PER_SIZE
SICLSP_INSTANCES_PER_SIZE = INSTANCES_PER_SIZE

# --- Gurobi (TRUSTED GROUND-TRUTH model only) ---
# These settings apply to the manually implemented benchmark formulations in
# src/models/. They do NOT apply to Gurobi code generated by GPT-4o in the
# Code-Based treatment — there, Gurobi solves whatever formulation the model
# produced, which is not guaranteed to represent the intended problem.
GUROBI_TIME_LIMIT = 300   # seconds per solve
GUROBI_MIP_GAP = 0.0      # ground truth must be provably optimal

# --- Model / API parameters ---
# Pinned, versioned model identifier instead of the "gpt-4o" alias:
# non-determinism studies show output variance even at temperature 0, so an
# unversioned alias would add a second uncontrolled factor.
CHATGPT_MODEL = "gpt-4o-2024-08-06"
TEMPERATURE = 0.0

# Repetitions per instance and treatment.
# Ten repetitions measure run-to-run variation/consistency under otherwise
# fixed conditions. They are NOT ten statistically independent optimization
# instances — they are repeated model runs nested within the same generated
# instance, and later statistical analysis must preserve that distinction.
N_RUNS_PER_INSTANCE = 10

# --- Code-Based treatment ---
# Maximum number of TECHNICAL debugging rounds after the initial generation.
# Debugging feedback is restricted to execution/formatting failures; no
# feasibility, objective or optimality information is ever returned to the
# model (see src/chatgpt/run_code_based.py).
MAX_DEBUG_ITERATIONS = 5

# Hard timeout for executing generated code in the sandbox subprocess.
CODE_EXECUTION_TIMEOUT = 60
